// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"

void myfile(lv_event_t * e)
{
	// Your code here
}

void musiclist(lv_event_t * e)
{
	// Your code here
}

void backevent(lv_event_t * e)
{
	// Your code here
}
